[[redirects]]
  from = "/docs/guides/webauthn/"
  to = "/docs/guides/html-and-js/"

[[redirects]]
  from = "/docs/resources/jwt-token/"
  to = "/docs/howto/handle-jwt-token/"

[[redirects]]
  from = "/docs/dev-integrations/email-whitelisting/"
  to = "/docs/howto/email-whitelisting/"

[[redirects]]
  from = "/docs/howto/jwt-token/"
  to = "/docs/howto/handle-jwt-token/"

[[redirects]]
  from = "/docs/howto/asp.net/"
  to = "/docs/howto/asp-dot-net/"

  [[redirects]]
  from = "/docs/guides/android/"
  to = "/docs/sdks/android/"