[[redirects]]
  from = "/docs/guides/webauthn/"
  to = "/docs/guides/html-and-js/"

[[redirects]]
  from = "/docs/resources/jwt-token/"
  to = "/docs/howto/handle-jwt-token/"

[[redirects]]
  from = "/docs/dev-integrations/email-whitelisting/"
  to = "/docs/howto/integrate-mailazy/"

[[redirects]]
  from = "/docs/howto/jwt-token/"
  to = "/docs/howto/handle-jwt-token/"

[[redirects]]
  from = "/docs/sdks/asp.net/"
  to = "/docs/sdks/asp-dot-net/"

  [[redirects]]
  from = "/docs/guides/android/"
  to = "/docs/sdks/android/"

  [[redirects]]
  from = "/docs/howto/phone-login/"
  to = "/docs/howto/add-sms-authentication/"

  [[redirects]]
  from = "/docs/howto/email-whitelisting/"
  to = "/docs/howto/integrate-mailazy/"